name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Compile and lint
        run: |
          yarn run build
          yarn run lint
      - name: Check code formatting
        run: yarn format:check
      - uses: nevermined-io/nvm-tools-actions@v0.14.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          estuary: 'true'
          # TODO: Update to tagged versions when everything is relased and in main branches
          contracts-version: 'latest'
          node: 'false'
      - name: Check artifacts
        run: |
          nvm-tools copy-artifacts ./artifacts
          ls -l artifacts
          nvm-tools copy-circuits ./circuits
          ls -l circuits
      - name: Run node
        run: |
          yarn setup:dev
          yarn start &

          # wait for node to start
          wget --retry-connrefused --tries=20 http://localhost:8030
      - name: Run tests
        run: |
          # HDWalletProvider keeps jest from exiting
          yarn integration --detectOpenHandles
